import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'


export default function Home() {
  return (
   
    <div className={styles.container}>
   
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
         <a>Coding Meow</a>
        </h1>
        <div className={styles.imgwrap}>
      <Image className={styles.img} src={'/christopher-gower-m_HRfLhgABo-unsplash.jpg'} width={418} height={313}/>
      </div>
       <p className={styles.description}>
          Live to Code, Code to Live
        </p>
        
    

        <div className="blog">
       
          <h2 className={styles.pop}>Popular Blogs</h2>
          <div className={styles.BlogPost}>
            <h3>How to learn Next js in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.
            </p>
          </div>
          <div className={styles.BlogPost}>

            <h3>How to learn Next js in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.
            </p>
          </div>
          
          <div className={styles.BlogPost}>
            <h3>How to learn Next js in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.
            </p>
          </div>
        </div>
      </main>

     
    </div>
  )
}
